<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>LIFEMUSIC - Login </title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Meta -->
  <link rel="manifest" href="/images/favicon/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/images/favicon/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">

  <!-- Favicon : generated by https://www.favicon-generator.org/  -->
  <link rel="apple-touch-icon" sizes="57x57" href="/images/favicon/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/images/favicon/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/images/favicon/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/images/favicon/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/images/favicon/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/images/favicon/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/images/favicon/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/images/favicon/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192" href="/images/favicon/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/images/favicon/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon/favicon-16x16.png">

  <!-- Bootstrap 4 -->
  <link rel="stylesheet" type="text/css" href="/lib/bootstrap/dist/css/bootstrap.min.css" />
  <script src="/lib/jquery/dist/jquery.min.js"></script>
  <script src="/lib/popper.js/dist/umd/popper.min.js"></script>
  <script src="/lib/bootstrap/dist/js/bootstrap.min.js"></script>

  <!-- Bootstrap-Select -->
  <link rel="stylesheet" href="/lib/bootstrap-select/dist/css/bootstrap-select.min.css">
  <script src="/lib/bootstrap-select/dist/js/bootstrap-select.min.js"></script>

  <!-- Font-Awesome -->
  <link rel="stylesheet" type="text/css" href="/lib/font-awesome/css/font-awesome.min.css" />

  <!-- CSS -->
  <link rel="stylesheet" type="text/css" media="screen" href="/css/main.css">
  <link rel="stylesheet" type="text/css" media="screen" href="/css/signin.css">

  <!-- Javascript -->
  <script src="/js/main.js"></script>  
  
</head>
<body class="text-center"> 
  <form class="form-signin">
    <img class="mb-4" src="/images/favicon/android-icon-72x72.png" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputId" class="sr-only">ID</label>
    <input type="text" id="inputId" class="form-control" placeholder="ID" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2020</p>
  </form>
</body>
</html>