/*** 1. Categories ***/

-- READY
-- TRUNCATE TABLE categories;

-- SELECT * from categories c2 ;
-- SELECT * from genres g2 ;

-- 1-1. Genres
-- depth lv1
insert into categories (`type` , name , parent_id ) values ('GENRE', 'African', null);
insert into categories (`type` , name , parent_id ) values ('GENRE', 'Asian', null);
insert into categories (`type` , name , parent_id ) values ('GENRE', 'Avant-garde', null);
insert into categories (`type` , name , parent_id ) values ('GENRE', 'Blues', null);
insert into categories (`type` , name , parent_id ) values ('GENRE', 'Caribbean', null);
insert into categories (`type` , name , parent_id ) values ('GENRE', 'Comedy', null);
insert into categories (`type` , name , parent_id ) values ('GENRE', 'Country', null);
insert into categories (`type` , name , parent_id ) values ('GENRE', 'Easy listening', null);
insert into categories (`type` , name , parent_id ) values ('GENRE', 'Electronic', null);
insert into categories (`type` , name , parent_id ) values ('GENRE', 'House', null);
insert into categories (`type` , name , parent_id ) values ('GENRE', 'Flamenco', null);
insert into categories (`type` , name , parent_id ) values ('GENRE', 'Folk', null);
insert into categories (`type` , name , parent_id ) values ('GENRE', 'Hip hop', null);
insert into categories (`type` , name , parent_id ) values ('GENRE', 'Jazz', null);
insert into categories (`type` , name , parent_id ) values ('GENRE', 'Latin', null);
insert into categories (`type` , name , parent_id ) values ('GENRE', 'Pop', null);
insert into categories (`type` , name , parent_id ) values ('GENRE', 'R&B and soul', null);
insert into categories (`type` , name , parent_id ) values ('GENRE', 'Rock', null);

-- depth lv2
    -- African
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Afrobeat', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'African hip hop', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'African heavy metal', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Apala', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Benga', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Boomba', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bongo Flava', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bikutsi', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Cape Jazz', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Chimurenga', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Congolese rumba', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Coupé-Décalé', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Fuji', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Genge', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Highlife', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hiplife', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Igbo highlife', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Igbo rap', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Isicathamiya', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Jit', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Jùjú', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Gqom', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Kadongo Kamu', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Kizomba', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Kuduro', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Kwaito', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Kwela', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Makossa', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Maloya', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Marabi', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Marrabenta', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Mbalax', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Mbaqanga', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Mbube', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Morna', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ndombolo', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Palm-wine', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Raï', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Sega', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Shangaan electro', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Soukous', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Kwassa kwassa', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Taarab', 1);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Zouglou', 1);    

    -- Asian
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Fijiri', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Khaliji', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Liwa', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Sawt', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'C-pop', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Cantopop', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Mandopop', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Taiwanese pop', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Chinese rock', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Enka', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hong Kong English pop', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'J-pop', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Japanese jazz', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Japanese rock', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Kayōkyoku', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'K-pop', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Korean hip hop', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Trot', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Asian Underground', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Baila', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Baul', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bhangra', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bhawaiya', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Goa trance', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Indian Classical', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hindustani Classical', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Carnatic', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Indian jazz', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Indian pop', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Indian rock', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Raga rock', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Lavani', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Morlam', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ragini', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Sufi rock', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dangdut', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Indo pop', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Luk thung', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Luk Krung', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Manila Sound', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Original Pilipino', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Mor lam', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Pinoy pop', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Pop sunda', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Thai string pop', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Thai pop', 2);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'V-pop', 2);

    -- Avant-garde
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Experimental', 3);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Noise', 3);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Harsh Noise', 3);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Harsh noise wall', 3);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Outsider music', 3);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Lo-fi', 3);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Musique concrète', 3);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electroacoustic', 3);

    -- Blues
    insert into categories (`type`, name, parent_id) values ('GENRE', 'African blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Blues rock', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Canadian blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Chicago blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Classic female blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Contemporary R&B', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Country blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Delta blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Detroit blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electric blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Gospel blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hill country blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Jump blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Kansas City blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Louisiana blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Memphis blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Piedmont blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Punk blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Rhythm and blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Soul blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'St. Louis blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Swamp blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Texas blues', 4);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'West Coast blues', 4);

    -- Caribbean
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Baithak Gana', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Dancehall', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Bouyon', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Cadence-lypso', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Calypso', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Cha-cha-chá', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Chutney', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Chutney soca', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Chutney parang', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Compas', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Mambo', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Merengue', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Méringue', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Mozambique', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Pichakaree', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Punta', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Punta Rock', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Rasin', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Reggae', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Dub', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Lovers rock', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Ragga', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Ragga jungle', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Reggae fusion', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Reggaeton', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Rocksteady', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Rumba', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Ska', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Two-tone', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Ska punk', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Salsa', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Son cubano', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Songo', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Soca', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Power Soca', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Timba', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Twoubadou', 5);
     insert into categories (`type`, name, parent_id) values ('GENRE', 'Zouk', 5);  

    -- Comedy
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Comedy', 6);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Comedy rock', 6);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Novelty', 6);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Parody', 6);

    -- Country
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Alternative country', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Cowpunk', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Americana', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Australian country', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bakersfield sound', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bluegrass', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Progressive bluegrass', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Cajun', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Cajun fiddle', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Christian country', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Classic country', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Close harmony', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Country blues', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Country pop', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Country rap', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Country rock', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Cowboy', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Cowboy pop', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dansband', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hokum', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Honky tonk', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Música sertaneja', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Nashville sound', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Neotraditional country', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Outlaw country', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Progressive country', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Red Dirt', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Rockabilly', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hellbilly', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Psychobilly', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Texas country', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Traditional country', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Truck-driving country', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Western swing', 7);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Zydeco', 7);

    -- Easy listening
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Background music', 8);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Beautiful music', 8);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Elevator music', 8);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Furniture music', 8);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Lounge music', 8);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Middle of the road music', 8);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'New-age music', 8);

    -- Electronic
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ambient', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ambient dub', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dark ambient', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dungeon synth', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Drone', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Space', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Illbient', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Psybient', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Breakbeat', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Acid breaks', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Baltimore club', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Jersey club', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Big beat', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Broken beat', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Florida breaks', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Nu-funk', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Miami bass', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Nu skool breaks', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Disco', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Afro/Cosmic', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Disco polo', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Euro disco', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Italo disco', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Nu-disco', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Space disco', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Downtempo', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Acid jazz', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Chill-out', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'New-age', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Space', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Trip hop', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Drum and bass', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Liquid funk', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Neurofunk', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Neurohop', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Jump-up', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Darkstep', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Drumstep', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Funkstep', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hardstep', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Sambass', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Techstep', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dub', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ambient dub', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dancehall', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dub poetry', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dub reggae', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dub techno', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dubstep', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dubtronica', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electro', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Freestyle', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electro-industrial', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electroacoustic', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Acousmatic', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Musique concrète', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Modular', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electronic dance music', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electronic rock', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Alternative dance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Indietronica', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Coldwave', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dance-punk', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dark wave', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electroclash', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electronicore', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Nintendocore', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electropunk', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ethereal wave', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Krautrock', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Minimal wave', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'New rave', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Nu-gaze', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Space rock', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Synthpop', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electronica', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dubtronica', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Folktronica', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Funktronica', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Laptronica', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Livetronica', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ethnic electronica', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Al Jeel', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Arabic pop', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Asian underground', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bhangra', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bhangragga', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'C-pop', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Cantopop', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'J-pop', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'City pop', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Shibuya-kei', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'K-pop', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Worldbeat', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hardcore', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Gabber', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', '4-beat', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Breakbeat hardcore', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bouncy techno', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Breakcore', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hardbass', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Digital hardcore', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Darkcore', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Happy hardcore', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Mákina', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Speedcore', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Splittercore', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Extratone', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'UK hardcore', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hardstyle', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dubstyle', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Jumpstyle', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Lento violento', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hi-NRG', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Eurobeat', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Eurodance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bubblegum dance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hard dance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Italo dance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hip hop', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Breakbeat', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Crunk', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electro', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hip house', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Trap', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Trap EDM', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Drill', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'UK drill', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'below', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Industrial', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Aggrotech', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electrogrind', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electro-industrial', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dark ambient', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dark electro', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electronic body', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Futurepop', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'New beat', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Industrial metal', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Industrial rock', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Japanoise', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Neue Deutsche Härte', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Power electronics', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Death industrial', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Power noise', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Intelligent dance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Glitch', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Glitch Hop', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Wonky', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Oldschool jungle', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Darkcore', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ragga jungle', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Raggacore', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Post-disco', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Boogie', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electropop', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Chillwave', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Vaporwave', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hardvapour', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dance-pop', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dance-rock', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Techno', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Acid techno', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Detroit techno', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dub techno', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hardtechno', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Industrial techno', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Minimal techno', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'New beat', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Nortec', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Tecno brega', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Trance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Acid trance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Balearic trance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dream trance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Euro-trance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hard trance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Nitzhonot', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Psychedelic trance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Full on', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Suomisaundi', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Goa trance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Progressive trance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Tech trance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Uplifting trance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Vocal trance', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'UK garage', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', '2-step garage', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dubstep', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Brostep', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Drumstep', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Reggaestep', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Breakstep', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Future garage', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Grime', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'UK drill', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Grindie', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Speed garage', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bassline', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'UK funky', 9);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Nightcore', 9);    

    -- House
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Acid house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ambient house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Balearic beat', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Chicago house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Deep house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Diva house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hardbag', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electro house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Big room house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Complextro', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dutch house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Fidget house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'French house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Nu-disco', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Funky house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Future house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Garage house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ghetto house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ghettotech', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Juke house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Footwork', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hard house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hard dance', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hip house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Italo house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Nu jazz', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Kidandali', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Kwaito', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Latin house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Microhouse', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Moombahton', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Moombahcore', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Progressive house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Rara tech', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Tech house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Tribal house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Tropical house', 10);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Witch house', 10);

    -- Flamenco
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Toná', 11);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Martinetes', 11);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Tonás', 11);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bulerías', 11);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Alegrías', 11);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Peteneras', 11);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Fandangos', 11);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Tango', 11);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Cantes de ida y vuelta', 11);

    -- Folk
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Anti-folk', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Turbo-folk', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Celtic', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Chalga', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Filk', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Folk rock', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Folktronica', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Freak folk', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Indie folk', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Industrial folk', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Neofolk', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Progressive folk', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Protest song', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Psychedelic folk', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Singer-songwriter', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Skiffle', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Sung poetry', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Traditional Folk', 12);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Western music', 12);

    -- Hip hop
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Alternative hip hop', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Australian hip hop', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bongo Flava', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Boom bap', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'British hip hop', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Chap hop', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Chopper', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Christian hip hop', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Cloud rap', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Conscious hip hop', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Crunk', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Crunkcore', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Drill', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electro', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Emo hip hop', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Experimental hip hop', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'G-funk', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ghetto house', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ghettotech', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Golden age hip hop', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Grime', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hardcore hip hop', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hip house', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hiplife', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hip pop', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hyphy', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Industrial hip hop', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Instrumental hip hop', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Jazz rap', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Jersey club', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Kwaito', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Lyrical hip hop', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Low Bap', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Merenrap', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Motswako', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Mumble rap', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Nerdcore', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'New jack swing', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'New school hip hop', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Old school hip hop', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Political hip hop', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ragga', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Reggaeton', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Snap', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Jerkin''', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Trap', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Urban Pasifika', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Emo rap', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'K-rap', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'J-rap', 13);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Horrorcore', 13);

    -- Jazz
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Acid jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Afro-Cuban jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Avant-garde jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bebop', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Boogie-woogie', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bossa nova', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'British dance band', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Cape jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Chamber jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Continental jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Cool jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Crossover jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dixieland', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ethno jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'European free jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Free funk', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Free improvisation', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Free jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Gypsy jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hard bop', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Jazz blues', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Jazz-funk', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Jazz fusion', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Jazz rap', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Jazz rock', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Kansas City blues', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Kansas City jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Latin jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Livetronica', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'M-Base', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Mainstream jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Modal jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Neo-bop jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Neo-swing', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Novelty ragtime', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Nu jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Orchestral jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Post-bop', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Progressive jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Psychedelic jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Punk jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ragtime', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Shibuya-kei', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ska jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Smooth jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Soul jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Stride jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Straight-ahead jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Swing', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Third stream', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Trad jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Vocal jazz', 14);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'West Coast jazz', 14);

    -- Latin
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Axé', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Brazilian rock', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Brega', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Tecnobrega', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Choro', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Forró', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Frevo', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Funk Carioca', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Lambada', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Maracatu', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Música popular brasileira', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Tropicalia', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Música sertaneja', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Samba', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Pagode', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Samba rock', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Latin Christian', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Latin jazz', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Afro-Cuban jazz', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bossa Nova', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Latin pop', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Latin ballad', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Latin rock', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Latin alternative', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Rock en Español', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Reggaeton', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Latin trap', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Regional Mexican', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Banda', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Grupera', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Mariachi', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Ranchera', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Norteño', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Tejano', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Turbo-folk', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bullerengue', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Fado', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Huayno', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Mexican son', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Música criolla', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Nueva canción', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Tropical', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bachata', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bolero', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Criolla', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Cumbia', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Chicha', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Porro', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Guajira', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Mambo', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Merengue', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Cuban rumba', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Salsa', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Salsa romántica', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Son', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Timba', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Tropipop', 15);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Vallenato', 15);

    -- Pop
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Adult contemporary', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Arabic pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Baroque pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Brill Building', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Britpop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Bubblegum pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Canción', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Canzone', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Chalga', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Chanson', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Christian pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Classical crossover', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Country pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'C-pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hokkien pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Mandopop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dance-pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Disco polo', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electropop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Europop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Austropop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Eurobeat', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'French pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Italo dance', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Italo disco', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Laïkó', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Latin pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Nederpop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Russian pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Fado', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Folk pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Iranian pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Indie pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'J-pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Jangle pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'K-pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Korean rock', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'T'ong guitar', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Trot', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Swamp pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Mexican pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'New Romantic', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Operatic pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Power pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Soft rock', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Pop punk', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Neon pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Emo pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Pop soul', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Progressive pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Psychedelic pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Rebetiko', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Schlager', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Sophisti-pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Space age pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Sunshine pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Surf', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Synthpop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Teen pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Traditional pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Turkish pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Vispop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Wonky pop', 16);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Worldbeat', 16);

    -- R&B and soul
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Contemporary R&B', 17);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Disco', 17);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Funk', 17);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Deep funk', 17);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Freestyle', 17);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Go-go', 17);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'P-Funk', 17);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Post-disco', 17);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Boogie', 17);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Alternative R&B', 17);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'New jack swing', 17);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Rhythm and blues', 17);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Soul', 17);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Blue-eyed soul', 17);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Northern soul', 17);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Neo soul', 17);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Psychedelic Soul', 17);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Southern soul', 17);

    -- Rock
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Alternative rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Britpop', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Post-Britpop', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Shoegaze', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dream Pop', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Grunge', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Post-grunge', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Indie rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dunedin Sound', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Math rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Post-punk revival', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Sadcore', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Slowcore', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Beat', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Christian rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Dark cabaret', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electronic rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Electronicore', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Experimental rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Art rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Industrial rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Post-punk', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Gothic rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'No wave', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Noise rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Post-rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Post-metal', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Folk rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Garage rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Glam rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Hard rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'below', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Jazz rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'New wave', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'World fusion', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Paisley Underground', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Desert rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Pop rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Soft rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Progressive rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Canterbury scene', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Krautrock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'New prog', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Rock in Opposition', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Space rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Psychedelic rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Acid rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Freakbeat', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Neo-psychedelia', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Raga rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'below', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Rap rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Rapcore', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Rock and roll', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Southern rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Stoner rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Sufi rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Surf rock', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Visual kei', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Nagoya kei', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Worldbeat', 18);
    insert into categories (`type`, name, parent_id) values ('GENRE', 'Wrock', 18);